from __future__ import annotations

from typing import Dict, List


DEFAULT_HOME_LIGHT_LIST_IDS = [
    "douban-top50",
    "nolan",
    "miyazaki",
    "shinkai",
    "chinese-highscore",
    "wong-kar-wai",
    "disney-animation",
    "couple-debate",
    "spielberg",
]

LIGHT_LIST_SEGMENTS: Dict[str, str] = {
    "douban-top50": "category",
    "nolan": "director",
    "miyazaki": "director",
    "shinkai": "director",
    "chinese-highscore": "category",
    "wong-kar-wai": "director",
    "disney-animation": "category",
    "couple-debate": "category",
}


ROTATION_CANDIDATE_TEMPLATES: List[Dict[str, object]] = [
    {
        "id": "spielberg",
        "name": "斯皮尔伯格电影榜",
        "theme": "我的斯皮尔伯格电影榜",
        "tagline": "从冒险、童年到历史创伤，排出你的斯皮尔伯格顺序。",
        "top_k": 10,
        "seed_text": "spielberg-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合想比较商业奇观、成长故事与历史题材的影迷。",
        "card_poster_title": "辛德勒的名单",
        "items": [
            "大白鲨", "第三类接触", "E.T.外星人", "夺宝奇兵", "紫色", "侏罗纪公园",
            "辛德勒的名单", "拯救大兵瑞恩", "猫鼠游戏", "慕尼黑", "林肯", "西区故事",
        ],
    },
    {
        "id": "tarantino",
        "name": "昆汀电影狠角色榜",
        "theme": "我的昆汀·塔伦蒂诺电影榜",
        "tagline": "对白、复仇与类型片狂欢，哪一部最对你的胃口？",
        "top_k": 8,
        "seed_text": "tarantino-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合喜欢强风格对白、非线性叙事和类型混搭的用户。",
        "card_poster_title": "低俗小说",
        "items": [
            "落水狗", "低俗小说", "杰基·布朗", "杀死比尔", "杀死比尔2", "金刚不坏",
            "无耻混蛋", "被解救的姜戈", "八恶人", "好莱坞往事",
        ],
    },
    {
        "id": "denis-villeneuve",
        "name": "维伦纽瓦科幻与迷局",
        "theme": "我的丹尼斯·维伦纽瓦电影榜",
        "tagline": "从现实迷局走向宏大科幻，排出你的冷峻震撼时刻。",
        "top_k": 8,
        "seed_text": "denis-villeneuve-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合喜欢沉浸氛围、道德困境和硬核科幻的用户。",
        "card_poster_title": "降临",
        "items": [
            "焦土之城", "囚徒", "宿敌", "边境杀手", "降临", "银翼杀手2049", "沙丘", "沙丘2",
        ],
    },
    {
        "id": "david-fincher",
        "name": "大卫·芬奇暗黑电影榜",
        "theme": "我的大卫·芬奇电影榜",
        "tagline": "犯罪、执念与冷感影像，哪一部最让你后背发凉？",
        "top_k": 10,
        "seed_text": "david-fincher-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合偏爱悬疑、犯罪、心理博弈和精密叙事的用户。",
        "card_poster_title": "搏击俱乐部",
        "items": [
            "异形3", "七宗罪", "心理游戏", "搏击俱乐部", "战栗空间", "十二宫",
            "本杰明·巴顿奇事", "社交网络", "龙纹身的女孩", "消失的爱人", "曼克", "杀手",
        ],
    },
    {
        "id": "bong-joon-ho",
        "name": "奉俊昊类型电影榜",
        "theme": "我的奉俊昊电影榜",
        "tagline": "黑色幽默、阶层寓言与怪物想象，排出你的奉俊昊顺序。",
        "top_k": 8,
        "seed_text": "bong-joon-ho-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合喜欢社会寓言与类型片混搭的韩国电影观众。",
        "card_poster_title": "寄生虫",
        "items": [
            "绑架门口狗", "杀人回忆", "汉江怪物", "母亲", "雪国列车", "玉子", "寄生虫", "米奇17号",
        ],
    },
    {
        "id": "hirokazu-koreeda",
        "name": "是枝裕和家庭手记",
        "theme": "我的是枝裕和电影榜",
        "tagline": "亲情、失去与日常缝隙，排出最打动你的温柔时刻。",
        "top_k": 8,
        "seed_text": "hirokazu-koreeda-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合喜欢生活流、家庭关系和克制情感表达的用户。",
        "card_poster_title": "小偷家族",
        "items": [
            "幻之光", "下一站天国", "无人知晓", "步履不停", "奇迹", "如父如子",
            "海街日记", "小偷家族", "掮客", "怪物",
        ],
    },
    {
        "id": "ang-lee",
        "name": "李安电影情感谱系",
        "theme": "我的李安电影榜",
        "tagline": "家庭、欲望与身份拉扯，排出你的李安电影坐标。",
        "top_k": 10,
        "seed_text": "ang-lee-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合想横跨华语家庭片、爱情片和好莱坞类型片的用户。",
        "card_poster_title": "卧虎藏龙",
        "items": [
            "推手", "喜宴", "饮食男女", "理智与情感", "卧虎藏龙", "绿巨人浩克",
            "断背山", "色戒", "少年派的奇幻漂流", "比利·林恩的中场战事", "双子杀手",
        ],
    },
    {
        "id": "zhang-yimou",
        "name": "张艺谋电影色彩榜",
        "theme": "我的张艺谋电影榜",
        "tagline": "乡土、历史与视觉奇观，排出你的张艺谋代表作。",
        "top_k": 10,
        "seed_text": "zhang-yimou-v1",
        "source": "builtin",
        "badge": "导演",
        "recommendation": "适合想比较早期现实主义与后期商业大片的华语影迷。",
        "card_poster_title": "活着",
        "items": [
            "红高粱", "菊豆", "大红灯笼高高挂", "秋菊打官司", "活着", "一个都不能少",
            "我的父亲母亲", "英雄", "十面埋伏", "归来", "一秒钟", "满江红",
        ],
    },
    {
        "id": "leonardo-dicaprio",
        "name": "莱昂纳多银幕角色榜",
        "theme": "我的莱昂纳多·迪卡普里奥电影榜",
        "tagline": "少年、骗子、疯子与野心家，哪个角色最难忘？",
        "top_k": 10,
        "seed_text": "leonardo-dicaprio-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合想比较莱昂纳多不同时期代表角色的用户。",
        "card_poster_title": "盗梦空间",
        "items": [
            "不一样的天空", "篮球日记", "罗密欧与朱丽叶", "泰坦尼克号", "猫鼠游戏", "飞行家",
            "无间行者", "禁闭岛", "盗梦空间", "华尔街之狼", "荒野猎人", "花月杀手",
        ],
    },
    {
        "id": "tom-hanks",
        "name": "汤姆·汉克斯人生角色榜",
        "theme": "我的汤姆·汉克斯电影榜",
        "tagline": "普通人的善意、坚持与命运，排出最打动你的角色。",
        "top_k": 10,
        "seed_text": "tom-hanks-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合喜欢温暖人物故事和经典好莱坞叙事的用户。",
        "card_poster_title": "阿甘正传",
        "items": [
            "飞越未来", "费城故事", "阿甘正传", "阿波罗13号", "拯救大兵瑞恩", "绿里奇迹",
            "荒岛余生", "猫鼠游戏", "幸福终点站", "菲利普船长", "萨利机长", "邻里美好的一天",
        ],
    },
    {
        "id": "cate-blanchett",
        "name": "凯特·布兰切特角色榜",
        "theme": "我的凯特·布兰切特电影榜",
        "tagline": "女王、艺术家与危险人物，排出她最迷人的银幕角色。",
        "top_k": 10,
        "seed_text": "cate-blanchett-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合关注表演层次、女性角色与作者电影的用户。",
        "card_poster_title": "卡罗尔",
        "items": [
            "伊丽莎白", "天才瑞普利", "指环王：护戒使者", "飞行家", "丑闻笔记",
            "本杰明·巴顿奇事", "蓝色茉莉", "卡罗尔", "雷神3：诸神黄昏", "不要抬头", "塔尔",
        ],
    },
    {
        "id": "denzel-washington",
        "name": "丹泽尔·华盛顿角色榜",
        "theme": "我的丹泽尔·华盛顿电影榜",
        "tagline": "领袖、警探与复杂父亲，哪次表演最有力量？",
        "top_k": 10,
        "seed_text": "denzel-washington-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合喜欢强人物弧光、犯罪片和历史传记的用户。",
        "card_poster_title": "训练日",
        "items": [
            "光荣战役", "马尔科姆X", "费城故事", "红潮风暴", "训练日", "怒火救援",
            "局内人", "美国黑帮", "迫降航班", "藩篱", "麦克白的悲剧",
        ],
    },
    {
        "id": "tony-leung",
        "name": "梁朝伟银幕角色榜",
        "theme": "我的梁朝伟电影榜",
        "tagline": "克制、孤独与江湖气，排出你心里的梁朝伟角色。",
        "top_k": 10,
        "seed_text": "tony-leung-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合香港电影与王家卫作品爱好者。",
        "card_poster_title": "花样年华",
        "items": [
            "悲情城市", "喋血街头", "辣手神探", "重庆森林", "春光乍泄", "花样年华",
            "无间道", "英雄", "2046", "色戒", "一代宗师", "尚气与十环传奇",
        ],
    },
    {
        "id": "maggie-cheung",
        "name": "张曼玉银幕风华榜",
        "theme": "我的张曼玉电影榜",
        "tagline": "从都市喜剧到时代女性，排出她最动人的银幕时刻。",
        "top_k": 10,
        "seed_text": "maggie-cheung-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合香港电影、女性表演和时代爱情片爱好者。",
        "card_poster_title": "阮玲玉",
        "items": [
            "警察故事", "旺角卡门", "阮玲玉", "新龙门客栈", "青蛇", "东邪西毒",
            "甜蜜蜜", "宋家皇朝", "花样年华", "英雄", "清洁",
        ],
    },
    {
        "id": "song-kang-ho",
        "name": "宋康昊韩国电影角色榜",
        "theme": "我的宋康昊电影榜",
        "tagline": "小人物、父亲与时代切面，排出最难忘的宋康昊角色。",
        "top_k": 10,
        "seed_text": "song-kang-ho-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合韩国电影爱好者，一次串起二十余年的代表作。",
        "card_poster_title": "杀人回忆",
        "items": [
            "绿鱼", "生死谍变", "共同警备区", "杀人回忆", "汉江怪物", "密阳",
            "蝙蝠", "雪国列车", "辩护人", "出租车司机", "寄生虫", "掮客",
        ],
    },
    {
        "id": "zhou-xun",
        "name": "周迅银幕角色榜",
        "theme": "我的周迅电影榜",
        "tagline": "灵气、执拗与时代女性，排出你最喜欢的周迅角色。",
        "top_k": 8,
        "seed_text": "zhou-xun-v1",
        "source": "builtin",
        "badge": "演员",
        "recommendation": "适合华语女性表演和多类型电影爱好者。",
        "card_poster_title": "苏州河",
        "items": [
            "苏州河", "巴尔扎克与小裁缝", "如果·爱", "李米的猜想", "画皮",
            "风声", "龙门飞甲", "明月几时有", "第十一回", "涉过愤怒的海",
        ],
    },
    {
        "id": "classic-scifi",
        "name": "科幻电影经典坐标",
        "theme": "我的科幻电影经典榜",
        "tagline": "从太空、机器到人类未来，排出你的科幻坐标。",
        "top_k": 10,
        "seed_text": "classic-scifi-v1",
        "source": "builtin",
        "badge": "科幻",
        "recommendation": "适合想比较不同年代科幻想象与哲学命题的用户。",
        "card_poster_title": "银翼杀手",
        "items": [
            "2001太空漫游", "银翼杀手", "异形", "终结者2：审判日", "侏罗纪公园", "黑客帝国",
            "人工智能", "少数派报告", "人类之子", "月球", "她", "降临",
        ],
    },
    {
        "id": "courtroom",
        "name": "法庭电影唇枪舌剑榜",
        "theme": "我的法庭电影榜",
        "tagline": "证词、偏见与真相交锋，哪场庭审最让你屏息？",
        "top_k": 8,
        "seed_text": "courtroom-v1",
        "source": "builtin",
        "badge": "法庭",
        "recommendation": "适合喜欢逻辑交锋、社会议题和密闭空间戏剧的用户。",
        "card_poster_title": "十二怒汉",
        "items": [
            "十二怒汉", "控方证人", "桃色血案", "纽伦堡的审判", "杀死一只知更鸟",
            "费城故事", "好人寥寥", "一级恐惧", "芝加哥七君子审判", "坠落的审判",
        ],
    },
    {
        "id": "heist-crime",
        "name": "劫案与犯罪电影榜",
        "theme": "我的劫案犯罪电影榜",
        "tagline": "计划、背叛与最后一票，排出最精彩的犯罪行动。",
        "top_k": 10,
        "seed_text": "heist-crime-v1",
        "source": "builtin",
        "badge": "犯罪",
        "recommendation": "适合喜欢团队行动、猫鼠博弈和高压节奏的用户。",
        "card_poster_title": "盗火线",
        "items": [
            "夜阑人未静", "大劫案", "偷天换日", "盗火线", "十一罗汉", "银行大劫案",
            "局内人", "城中大盗", "盗梦空间", "极盗车神", "赴汤蹈火", "夺金四贱客",
        ],
    },
    {
        "id": "coming-of-age",
        "name": "成长电影青春坐标",
        "theme": "我的成长电影榜",
        "tagline": "离家、友情与第一次告别，哪段成长最像你的青春？",
        "top_k": 10,
        "seed_text": "coming-of-age-v1",
        "source": "builtin",
        "badge": "成长",
        "recommendation": "适合想比较不同文化和年代青春经验的用户。",
        "card_poster_title": "伴我同行",
        "items": [
            "四百击", "青春残酷物语", "伴我同行", "死亡诗社", "阳光灿烂的日子", "猜火车",
            "燕尾蝶", "怦然心动", "少年时代", "月光男孩", "伯德小姐", "蜂鸟",
        ],
    },
    {
        "id": "horror",
        "name": "恐怖电影夜半榜",
        "theme": "我的恐怖电影榜",
        "tagline": "心理阴影、未知怪物与午夜诅咒，哪一部最让你不敢关灯？",
        "top_k": 10,
        "seed_text": "horror-v1",
        "source": "builtin",
        "badge": "恐怖",
        "recommendation": "适合想横跨心理恐怖、怪物片与亚洲恐怖的用户。",
        "card_poster_title": "闪灵",
        "items": [
            "惊魂记", "驱魔人", "闪灵", "异形", "怪形", "午夜凶铃",
            "咒怨", "鬼影", "生人勿进", "招魂", "逃出绝命镇", "遗传厄运",
        ],
    },
    {
        "id": "world-animation",
        "name": "世界动画电影奇想榜",
        "theme": "我的世界动画电影榜",
        "tagline": "日本赛博、欧洲手绘与现代实验动画，排出你的奇想世界。",
        "top_k": 10,
        "seed_text": "world-animation-v1",
        "source": "builtin",
        "badge": "动画",
        "recommendation": "适合想跳出单一厂牌，探索全球动画表达的用户。",
        "card_poster_title": "未麻的部屋",
        "items": [
            "阿基拉", "未麻的部屋", "千年女优", "疯狂约会美丽都", "机器人总动员", "我在伊朗长大",
            "与巴什尔跳华尔兹", "凯尔经的秘密", "养家之人", "红辣椒", "蜘蛛侠：平行宇宙", "机器人之梦",
        ],
    },
    {
        "id": "musical",
        "name": "歌舞电影高光榜",
        "theme": "我的歌舞电影榜",
        "tagline": "舞步、旋律与盛大告白，排出最想反复重看的歌舞时刻。",
        "top_k": 10,
        "seed_text": "musical-v1",
        "source": "builtin",
        "badge": "歌舞",
        "recommendation": "适合经典好莱坞、欧洲歌舞与现代音乐片爱好者。",
        "card_poster_title": "雨中曲",
        "items": [
            "雨中曲", "西区故事", "音乐之声", "瑟堡的雨伞", "欢乐满人间", "歌厅",
            "洛基恐怖秀", "红磨坊", "芝加哥", "追梦女郎", "爱乐之城", "马戏之王",
        ],
    },
    {
        "id": "sports",
        "name": "体育电影热血榜",
        "theme": "我的体育电影榜",
        "tagline": "胜负、团队与不肯认输，排出最让你热血的体育电影。",
        "top_k": 10,
        "seed_text": "sports-v1",
        "source": "builtin",
        "badge": "体育",
        "recommendation": "适合喜欢竞技过程、真实人物和逆境成长的用户。",
        "card_poster_title": "洛奇",
        "items": [
            "洛奇", "愤怒的公牛", "火战车", "梦幻之地", "光辉岁月", "百万美元宝贝",
            "弱点", "点球成金", "极速风流", "奎迪", "极速车王", "摔跤吧！爸爸",
        ],
    },
]


for priority, template in enumerate(ROTATION_CANDIDATE_TEMPLATES, 1):
    template_id = str(template["id"])
    template["card_poster_asset"] = f"assets/builtin_list_thumbnails/{template_id}.webp"
    template["rotation_segment"] = (
        "director" if priority <= 8 else "actor" if priority <= 16 else "category"
    )
    template["pool_priority"] = priority
    LIGHT_LIST_SEGMENTS[template_id] = str(template["rotation_segment"])


ROTATION_CANDIDATE_IDS = [str(template["id"]) for template in ROTATION_CANDIDATE_TEMPLATES]
